#pragma once

#define GAME_WINDOW_WIDTH 1000
#define GAME_WINDOW_HEIGHT 780

#define GAME_WINDOW_PADDINGS 100

#define BITO_HMENU 3050
#define TAKE_HMENU 3051

#define CARDS_AMOUNT 36
#define CARD_DISTANCE 12

#define CARDS_HAND_MARGIN 600
#define CARDS_ENEMY_HAND_MARGIN -60

#define TRUMP_MARGIN_TOP 200
#define TRUMP_MARGIN_LEFT 780

#define DECK_MARGIN_TOP 198
#define DECK_MARGIN_LEFT 840

#define QUITED_MARGIN_TOP 198
#define QUITED_MARGIN_LEFT 40

#define CARD_BOARD_MARGIN_TOP_FIRST 150
#define CARD_BOARD_MARGIN_TOP_SECOND 388
#define CARD_BOARD_MARGIN_LEFT 230
#define CARD_BOARD_DISTANSE 40